/**
 * Australian states, territories, capitals and a spread of suburbs and towns
 * that local-service doorway pages are typically minted for. Lower-case.
 * Multi-word names are kept as one entry and matched as a whole token group.
 */
export const PLACES: Set<string> = new Set(
	[
		// states and territories
		'wa',
		'western australia',
		'nsw',
		'new south wales',
		'vic',
		'qld',
		'queensland',
		'sa',
		'south australia',
		'tas',
		'tasmania',
		'nt',
		'northern territory',
		'act',
		'australian capital territory',
		// capitals
		'perth',
		'sydney',
		'melbourne',
		'brisbane',
		'adelaide',
		'hobart',
		'darwin',
		'canberra',
		// WA
		'mandurah',
		'rockingham',
		'baldivis',
		'kwinana',
		'fremantle',
		'joondalup',
		'wanneroo',
		'midland',
		'armadale',
		'canning vale',
		'cockburn',
		'bunbury',
		'busselton',
		'geraldton',
		'kalgoorlie',
		'albany',
		'ellenbrook',
		'scarborough',
		'subiaco',
		'victoria park',
		'gosnells',
		'thornlie',
		'morley',
		'bayswater',
		'belmont',
		'cannington',
		'byford',
		'pinjarra',
		'dawesville',
		'halls head',
		'secret harbour',
		'warnbro',
		'safety bay',
		'port kennedy',
		'yanchep',
		'two rocks',
		'butler',
		'clarkson',
		'mindarie',
		'hillarys',
		'karrinyup',
		'stirling',
		'osborne park',
		'balcatta',
		'malaga',
		'ballajura',
		'bassendean',
		'guildford',
		'kalamunda',
		'forrestfield',
		'maddington',
		'kelmscott',
		'mount lawley',
		'leederville',
		'nedlands',
		'claremont',
		'cottesloe',
		'mosman park',
		'applecross',
		'booragoon',
		'melville',
		'bibra lake',
		'spearwood',
		'hamilton hill',
		'coogee',
		'beeliar',
		'atwell',
		'harrisdale',
		'piara waters',
		'southern river',
		'jandakot',
		'leeming',
		'bull creek',
		'willetton',
		'riverton',
		'rossmoyne',
		'shelley',
		'bentley',
		'como',
		'south perth',
		'east perth',
		'north perth',
		'west perth',
		'northbridge',
		'highgate',
		'maylands',
		'inglewood',
		'dianella',
		'noranda',
		'beechboro',
		'kiara',
		'lockridge',
		'eden hill',
		'caversham',
		'swan view',
		'greenmount',
		'mundaring',
		'chidlow',
		'gidgegannup',
		'bullsbrook',
		'gingin',
		'lancelin',
		'jurien bay',
		'northam',
		'toodyay',
		'serpentine',
		'jarrahdale',
		'mundijong',
		'waroona',
		'harvey',
		'australind',
		'eaton',
		'collie',
		'donnybrook',
		'capel',
		'dunsborough',
		'margaret river',
		'augusta',
		'manjimup',
		'bridgetown',
		'denmark',
		'esperance',
		'broome',
		'karratha',
		'port hedland',
		'newman',
		'carnarvon',
		'exmouth',
		'derby',
		'kununurra',
		// NSW
		'newcastle',
		'wollongong',
		'central coast',
		'gosford',
		'wyong',
		'maitland',
		'cessnock',
		'lake macquarie',
		'port stephens',
		'parramatta',
		'penrith',
		'blacktown',
		'liverpool',
		'campbelltown',
		'camden',
		'hornsby',
		'ryde',
		'chatswood',
		'manly',
		'bondi',
		'randwick',
		'sutherland',
		'cronulla',
		'hurstville',
		'bankstown',
		'auburn',
		'strathfield',
		'burwood',
		'blue mountains',
		'katoomba',
		'castle hill',
		'baulkham hills',
		'coffs harbour',
		'port macquarie',
		'tamworth',
		'armidale',
		'dubbo',
		'bathurst',
		'wagga wagga',
		'albury',
		'goulburn',
		'queanbeyan',
		'nowra',
		'kiama',
		'shellharbour',
		'tweed heads',
		'byron bay',
		'lismore',
		'ballina',
		'grafton',
		// VIC
		'geelong',
		'ballarat',
		'bendigo',
		'shepparton',
		'mildura',
		'warrnambool',
		'frankston',
		'dandenong',
		'cranbourne',
		'pakenham',
		'berwick',
		'narre warren',
		'werribee',
		'sunshine',
		'footscray',
		'essendon',
		'moonee ponds',
		'preston',
		'reservoir',
		'heidelberg',
		'box hill',
		'ringwood',
		'croydon',
		'lilydale',
		'mornington',
		'rosebud',
		'traralgon',
		'morwell',
		'wodonga',
		'wangaratta',
		'horsham',
		'colac',
		'torquay',
		'ocean grove',
		// QLD
		'gold coast',
		'sunshine coast',
		'toowoomba',
		'townsville',
		'cairns',
		'mackay',
		'rockhampton',
		'bundaberg',
		'hervey bay',
		'gladstone',
		'ipswich',
		'logan',
		'redcliffe',
		'caboolture',
		'moreton bay',
		'redland',
		'southport',
		'surfers paradise',
		'robina',
		'burleigh heads',
		'coolangatta',
		'maroochydore',
		'caloundra',
		'noosa',
		'nambour',
		'gympie',
		'maryborough',
		'chermside',
		'carindale',
		'indooroopilly',
		'mount gravatt',
		// SA
		'mount gambier',
		'whyalla',
		'port augusta',
		'port lincoln',
		'murray bridge',
		'gawler',
		'salisbury',
		'modbury',
		'tea tree gully',
		'glenelg',
		'noarlunga',
		'mount barker',
		'victor harbor',
		'port pirie',
		// TAS / NT / ACT
		'launceston',
		'devonport',
		'burnie',
		'glenorchy',
		'alice springs',
		'palmerston',
		'katherine',
		'belconnen',
		'tuggeranong',
		'woden',
		'gungahlin',
		'queanbeyan'
	].map((p) => p.toLowerCase())
);

/**
 * Place names that are also ordinary English words. Kept out of PLACES so a
 * "Success Stories" or a "Winter sale" is never read as a doorway page: these
 * only count as a place when the title itself capitalises them.
 */
export const AMBIGUOUS_PLACES: Set<string> = new Set(
	[
		'success',
		'sale',
		'york',
		'kingston',
		'richmond',
		'windsor',
		'elizabeth',
		'victoria',
		'orange',
		'cleveland',
		'marion'
	].map((p) => p.toLowerCase())
);
